apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vitest-tls
  namespace: default
spec:
  secretName: vitest-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - vitest.uizb210.xyz
