apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod  # Reference the ClusterIssuer
spec:
  tls:
  - hosts:
      - vitest.uizb210.xyz  # Your domain
    secretName: mycoolapp-tls  # Secret to store the TLS certificate
  rules:
  - host: vitest.uizb210.xyz  # Your domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: user-login-service  # Updated service name
            port:
              number: 80
