apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-echo
spec:
  ingressClassName: nginx
  rules:
    - host: vitest.uizb210.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: user-login-service 
                port:
                  number: 80
