services:
  nginx:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/deptest.uizb210.xyz/fullchain.pem:/etc/letsencrypt/live/deptest.uizb210.xyz/fullchain.pem
      - /etc/letsencrypt/live/deptest.uizb210.xyz/privkey.pem:/etc/letsencrypt/live/deptest.uizb210.xyz/privkey.pem
    networks:
      - default
